name: eyecare_app
description: EyeCare mobile app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5

  # Needed by your code
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.3

  # Firebase (optional, can keep)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/babe.png

